<html>
<body>

<h2> INCLUYENDO FORMULARIO_REGISTRO HTML</h2>

<jsp:include page="Formulario_Registro.html"></jsp:include>

DE RELLENO DE RELLENO DE RELLENO DE RELLENO DE RELLENO </br>
DE RELLENO DE RELLENO DE RELLENO DE RELLENO DE RELLENO </br>
DE RELLENO DE RELLENO DE RELLENO DE RELLENO DE RELLENO </br>
DE RELLENO DE RELLENO DE RELLENO DE RELLENO DE RELLENO </br>
DE RELLENO DE RELLENO DE RELLENO DE RELLENO DE RELLENO </br>
DE RELLENO DE RELLENO DE RELLENO DE RELLENO DE RELLENO </br>

<jsp:include page="Fecha.jsp"></jsp:include>
</body>

</html>